version: '3.7'

services:
  app:
    build:
      context: ./
      target: prod
      dockerfile: ./Dockerfile
    container_name: flg_admin_pp
    env_file:
      - ./.env
    ports:
      - '5173:80'
    restart: 'unless-stopped'

